---
- name: Deploy OpenShift Project
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    project_name: ""
    project_dname: ""
    oc_host: ""
    oc_token: ""
    app_name: ""
    app_source: ""

  tasks:
    - name: Create Openshift Project
      oc:
        state: present
        host: "{{ oc_host }}"
        validate_certs: false
        inline:
          kind: ProjectRequest
          metadata:
            name: "{{ project_name}}"
          displayName: "{{ project_dname }}"
          description: This project was created using Ansible
        token: "{{ oc_token }}"

    - name: Create new app "{{ project_name }} and exposed it"
      shell: oc login https://"{{ oc_host }}":8443 --token="{{ oc_token}}" --insecure-skip-tls-verify=false && oc project "{{ project_name }}" && oc new-app --name={{ app_name }} openshift/php:5.6~"{{ app_source }}" && oc expose service "{{ app_name }}"
      args:
        creates: /tmp/"{{ app_name }}".log
